TensorRT QAT - Object Detection
nyunAI/nyuntam-vision pull request #10
Opened 2024-07-30 18:05 UTC by Akash-guna

Previous PR #9

2024-08-01 16:57 UTC, shwu-nyunai requested changes

2024-08-01 16:57 UTC, shwu-nyunai commented on quant/tensorrt/qat/main.py
> +        return subdirectories
os.walk could be used - _[ref docs](https://docs.python.org/3/library/os.html#os.walk)_

2024-08-01 16:57 UTC, shwu-nyunai commented on quant/tensorrt/qat/main.py
> +            f"python /mmrazor/tools/train.py current_quant_final.py --work-dir {self.job_path}"
same as above. (absolute path)

2024-08-01 16:57 UTC, shwu-nyunai commented on quant/tensorrt/qat/main.py
> +            f"docker exec -it Nyun_Kompress python mmdeploy/tools/deploy.py current_tensorrt_deploy_config.py current_quant_final.py {self.quantized_pth_location} demo_image.png"
why is a docker exec command used?

2024-08-01 16:57 UTC, shwu-nyunai commented on quant/tensorrt/qat/main.py
> +        shutil.move("/workspace/end2end.bin", os.path.join(self.model_path, "mds.bin"))
absolute paths.

2024-08-01 16:57 UTC, shwu-nyunai commented on quant/tensorrt/qat/utils.py
> +        f.write(config)
same as above.

2024-08-02 19:03 UTC, Akash-guna commented on quant/tensorrt/qat/main.py
> +        return subdirectories
Wasnt using it anywhere removed it

2024-08-02 19:04 UTC, Akash-guna commented on quant/tensorrt/qat/main.py
> +            f"python /mmrazor/tools/train.py current_quant_final.py --work-dir {self.job_path}"
changed (will be changed to vision/core/utils/mmrazortrain.py)

2024-08-02 19:05 UTC, Akash-guna commented on quant/tensorrt/qat/main.py
> +            f"docker exec -it Nyun_Kompress python mmdeploy/tools/deploy.py current_tensorrt_deploy_config.py current_quant_final.py {self.quantized_pth_location} demo_image.png"
Changed the flow , now the user needs to run the yaml twice to get a truely quantized model

2024-08-02 19:05 UTC, Akash-guna commented on quant/tensorrt/qat/utils.py
> +        f.write(cfg)
done

2024-08-05 04:38 UTC, shwu-nyunai requested changes

2024-08-05 04:38 UTC, shwu-nyunai commented on quant/tensorrt/qat/main.py
> +        self.work_dir = os.getcwd()
lets derive this at runtime.

2024-08-05 04:38 UTC, shwu-nyunai commented on quant/tensorrt/qat/main.py
> +                self.logger.info("Fake Quantization Successful")
no need to log if the exception is anyway going to be the last thing logged by the logger

2024-08-05 04:38 UTC, shwu-nyunai commented on quant/tensorrt/qat/main.py
> +                raise Exception(f"Fake Quantized Path is Not Present at {self.quantized_pth_location}")
same as above. the exception is logged in the logger. logging and then raising exception will make the logger redundant. we can avoid unnecessary logs.

2024-08-05 04:38 UTC, shwu-nyunai commented on core/utils/modelutils.py
> +    elif isinstance(loaded, nn.Module): ## add imports
the comment can be removed.

2024-08-05 09:01 UTC, shwu-nyunai approved these changes
lgtm. 👍🏻

2024-08-05 11:08 UTC, merged