MMRazor Prune - Object Detection
nyunAI/nyuntam-vision pull request #11
Opened 2024-07-30 18:09 UTC by Akash-guna

Previous PR #10

2024-08-01 17:02 UTC, shwu-nyunai requested changes

2024-08-01 17:02 UTC, shwu-nyunai commented on prune/mmrazorprune/main.py
> +        return
confirm file creation is either cleaned post job completion or created within job dir or cache dir

2024-08-01 17:02 UTC, shwu-nyunai commented on prune/mmrazorprune/main.py
> +        return
same as above.

2024-08-01 17:02 UTC, shwu-nyunai commented on prune/mmrazorprune/main.py
> +        cfg.dump("current_config_new.py")
as above. and subsequently all other such occurrences

2024-08-03 02:25 UTC, Akash-guna commented on prune/mmrazorprune/main.py
> +        return
Done

2024-08-03 02:26 UTC, Akash-guna commented on prune/mmrazorprune/main.py
> +        return
Rectified

2024-08-03 02:26 UTC, Akash-guna commented on prune/mmrazorprune/main.py
> +        cfg.dump("current_config_new.py")
Everything Rectified

2024-08-05 04:41 UTC, shwu-nyunai requested changes

2024-08-05 04:41 UTC, shwu-nyunai commented on prune/mmrazorprune/main.py
> +            "vision/core/utils/mmrazortrain.py",
lets derive this path at runtime.

2024-08-05 04:41 UTC, shwu-nyunai commented on prune/mmrazorprune/main.py
> +            f"{self.cache_path}current_config_new.py",
I believe there should be a forward slash (/) after self.cache_path

2024-08-05 08:40 UTC, shwu-nyunai requested changes

2024-08-05 08:40 UTC, shwu-nyunai commented on prune/mmrazorprune/main.py
> +        cfg.dump("current_config_new.py")
we are dumping this cfg, can't confirm if this is inside cache path? lets do a second check. if safe, kindly resolve.

2024-08-05 09:25 UTC, shwu-nyunai approved these changes

2024-08-05 11:09 UTC, Arnav0400 approved these changes

2024-08-05 11:09 UTC, merged