Object Detection , Segmentation and Pose Detection Datasets
nyunAI/nyuntam-vision pull request #6
Opened 2024-07-30 17:28 UTC by Akash-guna

Adds Object Detection , Segmentation and Pose Detection Datasets

Previous PR #5 (#4 was closed)

2024-08-01 11:58 UTC, shwu-nyunai requested changes
I see redundancies in BaseDataset classes; if possible, can we abstract out the common methods and extend/sub-class the download and modification utilities?

2024-08-01 11:58 UTC, shwu-nyunai commented on core/datasets/__init__.py
> +
is this coded needed?

2024-08-01 11:58 UTC, shwu-nyunai commented on core/datasets/classification/cifar.py
the only change in this file is adding the documentation to the class. I assume this is unintentional as a previous commit removed a similar document. Ignore if intentional.

2024-08-01 11:58 UTC, shwu-nyunai commented on core/datasets/object_detection/__init__.py
> +            raise Exception(f"unknown dataset{kwargs['name']}")
nitpick -

missing a space in error message. u in unknown could be capital.

2024-08-01 11:58 UTC, shwu-nyunai commented on core/datasets/object_detection/cocodetection.py
> +        ## To do: if shuffle is true, there should be 'val' in train test split
how important are these todo's?

2024-08-01 11:58 UTC, shwu-nyunai commented on core/datasets/object_detection/cocodetection.py
> +                pass
else block is not needed

2024-08-01 11:58 UTC, shwu-nyunai commented on core/datasets/object_detection/cocodetection.py
> +            )
if these files are large, we can make the downloads parallel?

this change can be moved to subsequent dev cycles or ft. issues. @Arnav0400  what's your opinion?

2024-08-01 11:58 UTC, shwu-nyunai commented on core/datasets/object_detection/dataset.py
> +            ), "Required param val missing in the defined split types (split_type)"
nitpick- 
I believe the assertion error message should be an f-string and the last word would be enclosed in '{}'.
ignore if intentional.

2024-08-01 11:58 UTC, shwu-nyunai commented on core/datasets/pose_estimation/cocopose.py
> +        ## To do: if shuffle is true, there should be 'val' in train test split
similar as above, ignore if not a problem.

2024-08-01 11:58 UTC, shwu-nyunai commented on core/datasets/pose_estimation/cocopose.py
> +            )
similar concerns as objectdet

2024-08-01 14:23 UTC, Akash-guna commented on core/datasets/object_detection/cocodetection.py
> +            )
This wont be used every time, and not every user will use this. So it is currently of a lower priority. Can be implemented in future.

2024-08-01 14:32 UTC, Akash-guna commented on core/datasets/__init__.py
> +
All comments mentioned in this pr are removed

2024-08-01 15:48 UTC, shwu-nyunai approved these changes

2024-08-01 15:48 UTC, shwu-nyunai commented on core/datasets/object_detection/dataset.py
> +            ), f"Required param val missing in the defined split types (split_type)"
there wasn't a need of making this an f-string if not using self.split_types in the error message 🙂

2024-08-01 15:59 UTC, shwu-nyunai commented
> I see redundancies in BaseDataset classes; if possible, can we abstract out the common methods and extend/sub-class the download, modification and other utilities?

any comments?

2024-08-05 08:57 UTC, shwu-nyunai approved these changes
awsm.

2024-08-05 11:06 UTC, Arnav0400 approved these changes

2024-08-05 11:06 UTC, merged