Object Detection , Segmentation and Pose Model Loading
nyunAI/nyuntam-vision pull request #7
Opened 2024-07-30 17:32 UTC by Akash-guna

Adds Object Detection , Segmentation and Pose Detection Model Loading

Previous PR #6

2024-08-01 13:08 UTC, shwu-nyunai requested changes

2024-08-01 13:08 UTC, shwu-nyunai commented on core/utils/modelutils.py
> +        return "MODEL"
do we need this method to infer this? we can directly perform an isinstance check and derive if a loaded weight is model or state_dict.

if we are keeping this logic, we should also confirm the type for the model
```suggestion
def get_state_dict_or_model(loaded):
    """
    Identifies if loaded file is a state dict or a nn.module
    """
    if isinstance(loaded, OrderedDict, dict):
        return "STATE_DICT"
    elif isinstance(loaded, nn.Module): ## add imports
        return "MODEL"
```

2024-08-01 13:08 UTC, shwu-nyunai commented on core/utils/modelutils.py
> +        return loaded, 0
as mentioned above, the two methods can be clubbed into one - 

```suggestion
def load_model_or_weights(path):
    "Loads the custom model / weights from the provided path"
    load = torch.load(path)
    if isinstance(load, nn.Module): ## add imports as necessary
        return load, 1
    elif isinstance(loaded, OrderedDict, dict):
        return load, 0
```

but imo, we can rather have a method that accepts a model and load_path and set the model accordingly.
would like to know more on the use case of this method.

2024-08-01 15:00 UTC, Akash-guna commented on core/models/ultralytics.py
> +    return model
Actually Ultralytics is currently not used for any models so it had to be removed added unneededly

2024-08-01 15:00 UTC, Akash-guna commented on core/utils/modelutils.py
> +        return "MODEL"
made this change

2024-08-02 11:18 UTC, shwu-nyunai approved these changes
lgtm.

2024-08-05 11:06 UTC, merged