NNCF - PTQ Object Detection & Classification
nyunAI/nyuntam-vision pull request #8
Opened 2024-07-30 17:44 UTC by Akash-guna

Previous PR #7

2024-08-01 13:35 UTC, shwu-nyunai requested changes

2024-08-01 13:35 UTC, shwu-nyunai commented on quant/__init__.py
> +def initialize_initialization(algoname, task):
lets use a more suitable name or simply override the dunder __getattr__

2024-08-01 13:35 UTC, shwu-nyunai commented on core/utils/mmutils.py
> +    cfg.dump("current_quant_final.py")
what is the directory where the dumps are happening? also, are these configs cleared after the job is completed? 
if not, lets either delete them post job or lets dump them inside inferred job dirs or cache dirs; 

same for all yamls, jsons, and intermediary files created.

2024-08-01 13:35 UTC, shwu-nyunai commented on quant/nncf/ptq/main.py
> +        self.logger.info(f"Experiment Arguments: {self.kwargs}")
we don't need to store the loggers in the classes; lets elevate the loggers out of the classes if loggers aren't dependent on the classes. 
same for all such occurrences.

2024-08-01 13:35 UTC, shwu-nyunai commented on quant/nncf/ptq/objectdetection.py
> +            f"python vision/core/utils/mmrazordeploy.py current_openvino_deploy_config.py current_quant_config.py {self.quantized_pth_location} demo_image.png"
lets have at least one runtime inferred path and refer that path for all paths we create. 
ideally, the repo root, or current file, or module root is inferred at runtime as follows and then extended to create the file paths;

```python
from pathlib import Path

ROOT = Path(__file__) # get the root path to module, or repo root 
extended_path = ROOT / "relative" / "path" / "from" / "root"
```

2024-08-01 13:35 UTC, shwu-nyunai commented on quant/nncf/ptq/objectdetection.py
> +        shutil.move("/workspace/nyuntam/end2end.bin", os.path.join(self.model_path, "mds.bin"))
lets avoid absolute paths; infer these relative to some runtime inferred path.

2024-08-01 13:35 UTC, shwu-nyunai commented on quant/nncf/ptq/utils.py
> +        f.write(cfg)
nitpick - 
ensure these paths are cleaned after the job completion or are created in cache/job paths

2024-08-01 13:35 UTC, shwu-nyunai commented on quant/nncf/ptq/utils.py
> +        f.write(config)
same as above. ignore if out of concern.

2024-08-02 08:24 UTC, Akash-guna commented on quant/nncf/ptq/main.py
> +        self.logger.info(f"Experiment Arguments: {self.kwargs}")
I suppose this change does not change any workflows / outputs so ignoring this for now

2024-08-02 09:06 UTC, Akash-guna commented on quant/__init__.py
> +def initialize_initialization(algoname, task):
in a later commit

2024-08-02 11:29 UTC, shwu-nyunai commented on quant/__init__.py
> +def initialize_initialization(algoname, task):
okay

2024-08-02 11:29 UTC, shwu-nyunai commented on quant/nncf/ptq/main.py
> +        self.logger.info(f"Experiment Arguments: {self.kwargs}")
okay

2024-08-02 11:30 UTC, shwu-nyunai approved these changes
lgtm

2024-08-05 11:06 UTC, Arnav0400 approved these changes

2024-08-05 11:07 UTC, merged